# Generated by Django 3.2.9 on 2022-01-25 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donation_request_view',
            fields=[
                ('ngo_name', models.CharField(default=None, max_length=50, primary_key=True, serialize=False)),
                ('domain', models.CharField(default=None, max_length=50)),
                ('head_of_ngo', models.CharField(default=None, max_length=50)),
                ('contactNo', models.CharField(default=None, max_length=10)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('donation_description', models.TextField(default=None)),
                ('donation_amount', models.CharField(default=None, max_length=10)),
            ],
            options={
                'db_table': 'post_request',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='donation_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_description', models.TextField(blank=True, default=0)),
                ('donation_amount', models.CharField(blank=True, default=None, max_length=15)),
                ('donation_request_user', models.CharField(blank=True, default=0, max_length=30)),
                ('status', models.CharField(choices=[('P', 'pending'), ('A', 'Approved'), ('w', 'Withdrawn')], default='PENDING', max_length=1)),
                ('admin_approved', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(blank=True, max_length=30)),
                ('domain', models.CharField(blank=True, max_length=20)),
                ('head_of_ngo', models.CharField(blank=True, max_length=30)),
                ('contactNo', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
