# Generated by Django 3.2.9 on 2022-01-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngo',
            name='Amount',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='ngo',
            name='Reason',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='donation_description',
            field=models.TextField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='donation_request_user',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
    ]
