# Generated by Django 3.2.9 on 2022-01-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='donation_amount',
            field=models.CharField(blank=True, default=0, max_length=15),
        ),
    ]
