# Generated by Django 3.2.9 on 2022-01-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'Approved'), ('w', 'Withdrawn')], default='PENDING', max_length=50),
        ),
    ]
