# Generated by Django 3.2.9 on 2022-01-26 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='donation_request_view',
        ),
        migrations.AlterModelOptions(
            name='donation_request',
            options={'managed': False},
        ),
    ]
