# Generated by Django 3.2.9 on 2022-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0002_auto_20220125_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo',
            old_name='Reason',
            new_name='Reason_for_donation',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='domain',
        ),
        migrations.AddField(
            model_name='ngo',
            name='ngo_current_user',
            field=models.CharField(blank=True, default=0, max_length=40),
        ),
        migrations.AddField(
            model_name='ngo',
            name='verification_status',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='ngo',
            name='Amount',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
