# Generated by Django 3.2.9 on 2022-01-26 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0002_alter_donation_request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation_request',
            name='Reason_for_donation',
        ),
        migrations.AddField(
            model_name='donation_request',
            name='Reason_for_donation_request',
            field=models.CharField(blank=True, default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='donation_request',
            name='contactNo',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='donation_request',
            name='email',
            field=models.EmailField(default=0, max_length=254),
        ),
        migrations.AddField(
            model_name='donation_request',
            name='head_of_ngo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
