# Generated by Django 3.2.9 on 2022-01-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0003_auto_20220126_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation_request',
            name='Reason_for_donation_request',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='donation_request_user',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='donation_request',
            name='ngo_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
