# Generated by Django 3.2.11 on 2022-02-02 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charapp', '0003_subscribe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
